### ISSUE TITLE
[Suggestion] show some screenShort

### ISSUE THREAD

**Issue by yichaosun** [Jules-Media/Modern-Calendar#1]
show some pic, bro

follow you

**Comment by juliandevelops** [comment]
It's not working as intended yet, so I can't really show a picture of it working. I will include one as soon as it's working.
Thanks for the suggestion

**Comment by yichaosun** [comment]
oh，I see.
you'r a young boy Student, great, go for it

as for material design ,much more theory and guide line
but there is no all-purpose solution for all platform, while material try to solve it, at least I think so.

the material lib, which contains material design module, can use it quickly for develop
